# Generated by Django 5.2.10 on 2026-01-23 06:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='paintings/')),
                ('year_created', models.IntegerField()),
                ('technique', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('customer_phone', models.CharField(db_index=True, max_length=15, verbose_name='شماره تماس')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='تعداد')),
                ('custom_message', models.TextField(blank=True, verbose_name='پیام سفارش')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='مرورگر')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('fraud', 'مشکوک')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('verification_code', models.CharField(blank=True, max_length=50, verbose_name='کد تأیید')),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='gallery.painting', verbose_name='اثر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
                'permissions': [('can_view_fraud_orders', 'مشاهده سفارش\u200cهای مشکوک'), ('can_export_orders', 'خروجی گرفتن از سفارش\u200cها')],
                'indexes': [models.Index(fields=['customer_phone', 'created_at'], name='gallery_ord_custome_75d64b_idx'), models.Index(fields=['status', 'created_at'], name='gallery_ord_status_971340_idx')],
            },
        ),
    ]
