# Generated by Django 5.2.10 on 2026-01-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='paintings/', verbose_name='تصویر اثر'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='technique',
            field=models.CharField(max_length=100, verbose_name='تکنیک'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='year_created',
            field=models.IntegerField(verbose_name='سال خلق'),
        ),
    ]
