# Generated by Django 5.2.3 on 2026-02-17 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_painting_image_alter_painting_technique_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='gallery_ord_custome_75d64b_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='gallery_ord_status_971340_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='custom_message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='painting',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='painting',
            name='technique',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_description',
            field=models.TextField(blank=True, verbose_name='توضیحات سفارش'),
        ),
        migrations.AddField(
            model_name='painting',
            name='artist_name',
            field=models.CharField(default='', max_length=200, verbose_name='نام هنری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='order',
            name='painting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='gallery.painting'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیح اثر'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(default='paintings/default.jpg', upload_to='paintings/', verbose_name='عکس اثر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='painting',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='نمایش داده شود'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='title',
            field=models.CharField(max_length=200, verbose_name='نام اثر'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='year_created',
            field=models.CharField(blank=True, max_length=10, verbose_name='سال خلق'),
        ),
    ]
